### ISSUE TITLE
final resolution goal

### ISSUE THREAD

**Issue by Afshinshafei** [mantariksh/231n_downscaling#1]
first of all thank you for this GREAT work.
I have a quick question, which is, in these models SRGAN and SRCNN, what is the final and goal resolution for the outputs. I mean, 2x, 4x or more enhancing the low-resolution data?
Thank you again for this great notebooks and work!

**Comment by lsspear** [comment]
We did 2x super resolution in this project. You can read about that, as well as other details of the data processing, in section 3.2 of the [Final Project Report](https://github.com/mantariksh/231n_downscaling/blob/master/Final_Project_Report.pdf) document in the repo as well.
